spring.application.name=expertDB

spring.datasource.url=jdbc:postgresql://localhost:5432/expert_db
spring.datasource.username=olivermazorodze
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=update

# spring.jpa.hibernate.ddl-auto=none
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

# Allow large JSON payloads for profile photo data URLs
server.tomcat.max-http-post-size=20MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB