spring.application.name=expertDB

spring.datasource.url=jdbc:postgresql://localhost:5432/expert_db
spring.datasource.username=olivermazorodze
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000