spring.application.name=expertDB

spring.datasource.url=jdbc:postgresql://localhost:5432/expert_db
spring.datasource.username=olivermazorodze
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver